load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "bitonic_sort",
    srcs = ["src/bitonic_sort.cpp"],
    hdrs = ["src/include/bitonic_sort.h"],
    visibility = ["//test:__pkg__"],
)